### ISSUE TITLE
Cloud is covering up the title text

### ISSUE THREAD

**Issue by Ilikepizza2** [iiitl/Sean-Halpin-Portfolio#2]
### The issue
![Screenshot_20230201_213956](https://user-images.githubusercontent.com/95919665/216098233-cdc7b45f-68d9-4062-b3aa-c46dbadfe671.png)

As visible in the screenshot, on smaller screens, the clouds cover up the text and other images. It would be better if they are below the text and the images. :)
A good beginning point would be looking into `z-index` css property for the clouds.

---

Remember to attach the screenshots showing the corrected clouds on the website in the PR.

**Comment by akhilender-bongirwar** [comment]
@Ilikepizza2 Sir, I would like to solve this issue. Please assign this to me.

**Comment by Ilikepizza2** [comment]
Sure @akhilender-bongirwar , go ahead.
You have been assigned. :)

**Comment by akhilender-bongirwar** [comment]
Sir , actually I made commit from main branch by mistake and added z index property.
![Screenshot (23)](https://user-images.githubusercontent.com/112749383/216809532-e820ac70-af69-4825-8ee1-8709968a9e3f.png)

**Comment by Ilikepizza2** [comment]
No problem, make a PR for this but from next time, *remember to make changes in a new branch*.

**Comment by Shivampatil22** [comment]
@Ilikepizza2 Sir, I would like to solve this issue.

**Comment by Ilikepizza2** [comment]
Sure @Shivampatil22, go ahead. You have been assigned. Good luck :)

**Comment by destroycompiler** [comment]
Sir I would like to work on the issue, could I have it assigned to me?

**Comment by Ilikepizza2** [comment]
Yes Sure @destroycompiler, you'll be the last one to be assigned this issue. You can start solving this.
